### ISSUE TITLE
filter_complex_script invalid argument

### ISSUE THREAD

**Issue by FlashlightET** [KenjiTakahashi/mpdecimate_trim#3] opened 2022-04-22 15:11 UTC
`Error opening file C:\Users\EZOGAM~1\AppData\Local\Temp\mpdecimate_trim.tkcnog8i.
Failed to set value 'C:\Users\EZOGAM~1\AppData\Local\Temp\mpdecimate_trim.tkcnog8i' for option 'filter_complex_script': Invalid argument
Error parsing global options: Invalid argument`

**Comment by KenjiTakahashi** [comment] 2022-04-26 23:25
Duplicate of #1. Please check in there, would be great if you could provide some more information as described.

**Closed as completed by KenjiTakahashi** 2022-04-26 23:25 UTC
